[PHP]
upload_max_filesize = 20M
post_max_size = 25M
max_execution_time = 300
max_input_time = 300
memory_limit = 256M
display_errors = Off
log_errors = On
error_log = /var/www/html/storage/logs/php-error.log
date.timezone = Asia/Jakarta

[Session]
session.save_handler = files

[File Uploads]
file_uploads = On
max_file_uploads = 20
