@extends('layouts.admin.admin')
@section('title', $title)
@section('content')
@include('pages.admin.modules.partials.flash')
<div class="ka-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Status absensi dan pengajuan Anda.</p></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card custom-card ka-card"><div class="card-body"><span class="text-muted small">Today</span><h5>{{ $todayAttendance?->status?->description ?? 'Not checked in' }}</h5></div></div></div><div class="col-md-3"><div class="card custom-card ka-card"><div class="card-body"><span class="text-muted small">Check In</span><h5>{{ $todayAttendance?->check_in_at?->format('H:i') ?? '-' }}</h5></div></div></div><div class="col-md-3"><div class="card custom-card ka-card"><div class="card-body"><span class="text-muted small">Check Out</span><h5>{{ $todayAttendance?->check_out_at?->format('H:i') ?? '-' }}</h5></div></div></div><div class="col-md-3"><div class="card custom-card ka-card"><div class="card-body"><span class="text-muted small">Pending</span><h5>{{ $pendingLeaves + $pendingCorrections }}</h5></div></div></div></div>
<div class="d-flex gap-2 mb-4"><a href="{{ route('employee.attendance.check-in') }}" class="btn btn-primary">Check-in</a><a href="{{ route('employee.attendance.check-out') }}" class="btn btn-outline-primary">Check-out</a><a href="{{ route('employee.attendance.history') }}" class="btn btn-light">History</a></div>
<div class="card custom-card ka-card"><div class="ka-card-header"><h5 class="mb-0">Recent Attendance</h5></div><div class="card-body p-0"><table class="table ka-table"><tbody>@forelse($monthlyAttendances as $item)<tr><td>{{ $item->attendance_date?->format('Y-m-d') }}</td><td>{{ $item->check_in_at?->format('H:i') ?? '-' }}</td><td>{{ $item->check_out_at?->format('H:i') ?? '-' }}</td><td>{{ $item->status?->description ?? '-' }}</td></tr>@empty<tr><td class="text-center text-muted py-4">No data</td></tr>@endforelse</tbody></table></div></div>
@endsection
