@extends('layouts.admin.admin')
@section('title', $title)
@push('styles')
<style>.ka-profile-shell{max-width:960px;margin:0 auto}.ka-profile-hero{border-radius:26px;background:linear-gradient(135deg,#0f4c81,#2563eb);color:#fff}.ka-profile-hero .text-muted{color:rgba(255,255,255,.72)!important}.ka-profile-avatar{width:72px;height:72px;border-radius:999px;background:rgba(255,255,255,.18);display:flex;align-items:center;justify-content:center;font-size:1.7rem;font-weight:800}.ka-form-card{border-radius:22px}</style>
@endpush
@section('content')
@include('pages.admin.modules.partials.flash')
<div class="ka-profile-shell">
    <div class="ka-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Edit data umum, username, email, dan password.</p></div></div>
    <div class="card custom-card ka-card ka-profile-hero mb-3"><div class="card-body p-4"><div class="d-flex gap-3 align-items-center"><div class="ka-profile-avatar">@if($profileImageUrl)<img src="{{ $profileImageUrl }}" alt="Profile" style="width:72px;height:72px;border-radius:999px;object-fit:cover">@else{{ strtoupper(substr($employee->full_name ?? 'E', 0, 1)) }}@endif</div><div><h3 class="text-white mb-1">{{ $employee->full_name }}</h3><div class="text-muted">{{ $employee->position?->name ?? '-' }} · {{ $employee->department?->name ?? '-' }}</div><div class="text-muted">{{ $employee->workLocation?->name ?? '-' }} · {{ $employee->shift?->name ?? '-' }}</div></div></div></div></div>
    <div class="card custom-card ka-card ka-form-card"><div class="card-body p-4"><form method="POST" action="{{ route('employee.profile.update') }}" enctype="multipart/form-data" class="row g-3">@csrf @method('PUT')<div class="col-12"><h5>Data Umum</h5></div><div class="col-md-6"><label class="form-label">Full Name</label><input name="full_name" value="{{ old('full_name', $employee->full_name) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Phone</label><input name="phone" value="{{ old('phone', $employee->phone) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Gender</label><select name="gender" class="form-control"><option value="">-</option><option value="male" @selected(old('gender', $employee->gender) === 'male')>male</option><option value="female" @selected(old('gender', $employee->gender) === 'female')>female</option></select></div><div class="col-md-6"><label class="form-label">Profile Photo</label><input type="file" name="profile_image" class="form-control" accept="image/png,image/jpeg,image/webp"><div class="text-muted small mt-1">JPG, PNG, WEBP max 2MB.</div></div><div class="col-12"><hr></div><div class="col-12"><h5>Akun Login</h5></div><div class="col-md-6"><label class="form-label">Username</label><input name="username" value="{{ old('username', $employee->user?->username) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" name="email" value="{{ old('email', $employee->user?->email) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Password Baru</label><input type="password" name="password" class="form-control" autocomplete="new-password"><div class="text-muted small mt-1">Kosongkan jika tidak ingin mengganti password.</div></div><div class="col-md-6"><label class="form-label">Konfirmasi Password</label><input type="password" name="password_confirmation" class="form-control" autocomplete="new-password"></div><div class="col-12"><button class="btn btn-primary btn-lg w-100">Save Profile</button></div></form></div></div>
</div>
@endsection
