@extends('layouts.admin.admin')
@section('title', $title)
@include('pages.hrd.partials.mobile-styles')
@section('content')
@include('pages.admin.modules.partials.flash')
<div class="ka-hrd-shell">
    <div class="ka-hrd-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Kelola jadwal kerja harian karyawan.</p></div></div>
    <div class="card custom-card ka-card mb-3"><div class="card-body"><form method="POST" action="{{ route('hrd.employee-schedules.store') }}" class="row g-2 ka-hrd-filter">@csrf<div class="col-12 col-md-3"><select name="employee_id" class="form-control" required><option value="">Karyawan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->full_name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><input type="date" name="schedule_date" class="form-control" required></div><div class="col-6 col-md-2"><select name="shift_id" class="form-control"><option value="">Shift</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><label class="form-check mt-2"><input type="checkbox" name="is_day_off" value="1" class="form-check-input"> Day Off</label></div><div class="col-6 col-md-2"><input type="text" name="note" class="form-control" placeholder="Catatan"></div><div class="col-12 col-md-1"><button class="btn btn-primary w-100">Simpan</button></div></form></div></div>
    <div class="card custom-card ka-card mb-3"><div class="card-body"><form class="row g-2 ka-hrd-filter"><div class="col-6 col-md-3"><input type="month" name="month" value="{{ request('month') }}" class="form-control"></div><div class="col-6 col-md-3"><select name="employee_id" class="form-control"><option value="">Karyawan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int) request('employee_id') === $employee->id)>{{ $employee->full_name }}</option>@endforeach</select></div><div class="col-6 col-md-3"><select name="department_id" class="form-control"><option value="">Departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((int) request('department_id') === $department->id)>{{ $department->name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
    <div class="card custom-card ka-card"><div class="card-body"><div class="ka-hrd-card-list">@forelse($items as $item)<div class="ka-hrd-item"><div class="d-flex justify-content-between gap-2"><div><div class="ka-hrd-item-title">{{ $item->employee?->full_name ?? '-' }}</div><div class="ka-hrd-meta">{{ $item->employee?->department?->name ?? '-' }}</div></div><span class="ka-hrd-pill">{{ $item->is_day_off ? 'Day Off' : ($item->shift?->name ?? '-') }}</span></div><div class="ka-hrd-meta mt-2">{{ $item->schedule_date?->format('d M Y') ?? '-' }} · {{ $item->note ?? '-' }}</div><form method="POST" action="{{ route('hrd.employee-schedules.destroy', $item->id) }}" class="mt-2">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></div>@empty<div class="text-center text-muted py-4">Belum ada jadwal.</div>@endforelse</div><div class="table-responsive ka-hrd-table"><table class="table ka-table"><thead><tr><th>Tanggal</th><th>Karyawan</th><th>Departemen</th><th>Shift</th><th>Day Off</th><th>Catatan</th><th>Aksi</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $item->schedule_date?->format('Y-m-d') ?? '-' }}</td><td>{{ $item->employee?->full_name ?? '-' }}</td><td>{{ $item->employee?->department?->name ?? '-' }}</td><td>{{ $item->shift?->name ?? '-' }}</td><td>{{ $item->is_day_off ? 'Ya' : 'Tidak' }}</td><td>{{ $item->note ?? '-' }}</td><td><form method="POST" action="{{ route('hrd.employee-schedules.destroy', $item->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada jadwal.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer bg-transparent">{{ $items->links() }}</div></div>
</div>
@endsection
