@extends('layouts.admin.admin')
@section('title', $title)
@include('pages.hrd.partials.mobile-styles')
@section('content')
@include('pages.admin.modules.partials.flash')
@php($needsReview = fn($item) => $item->is_need_approval || $item->check_in_is_inside_radius === false || $item->check_out_is_inside_radius === false)
@php($reviewStatus = fn($item) => $item->outside_radius_review_status_id === null ? 'pending' : ($item->outside_radius_review_status_id == \App\Models\Reference::query()->where('description','approved')->value('id') ? 'approved' : ($item->outside_radius_review_status_id == \App\Models\Reference::query()->where('description','rejected')->value('id') ? 'rejected' : 'pending')))
@php($statusColors = ['pending' => 'bg-warning text-dark', 'approved' => 'bg-success', 'rejected' => 'bg-danger'])
@php($pillColors = ['pending' => 'background:#f59e0b;color:#1e293b', 'approved' => 'background:#10b981;color:#fff', 'rejected' => 'background:#ef4444;color:#fff'])
<div class="ka-hrd-shell">
    <div class="ka-hrd-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Filter absensi harian berdasarkan karyawan, departemen, lokasi, shift, dan status.</p></div><div class="d-flex gap-2 flex-wrap"><a href="{{ route('hrd.attendances.map', request()->query()) }}" class="btn btn-primary">Peta Absensi</a><a href="{{ route('api.hrd.reports.daily-attendance.export', request()->query()) }}" class="btn btn-success">Export CSV</a></div></div>
    <div class="card custom-card ka-card mb-3"><div class="card-body"><form class="row g-2 ka-hrd-filter"><div class="col-6 col-md-2"><input type="date" name="date" value="{{ $date->format('Y-m-d') }}" class="form-control"></div><div class="col-6 col-md-2"><select name="employee_id" class="form-control"><option value="">Karyawan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int) request('employee_id') === $employee->id)>{{ $employee->full_name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><select name="department_id" class="form-control"><option value="">Departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((int) request('department_id') === $department->id)>{{ $department->name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><select name="work_location_id" class="form-control"><option value="">Lokasi Kerja</option>@foreach($workLocations as $location)<option value="{{ $location->id }}" @selected((int) request('work_location_id') === $location->id)>{{ $location->name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><select name="shift_id" class="form-control"><option value="">Shift</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}" @selected((int) request('shift_id') === $shift->id)>{{ $shift->name }}</option>@endforeach</select></div><div class="col-6 col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
    <div class="card custom-card ka-card"><div class="card-body"><div class="ka-hrd-card-list">@forelse($items as $item)
        @php($outside = $needsReview($item))
        @php($rev = $outside ? $reviewStatus($item) : null)
        <a href="{{ route('hrd.attendances.show', $item->id) }}" class="ka-hrd-item"><div class="d-flex justify-content-between gap-2"><div><div class="ka-hrd-item-title">{{ $item->employee?->full_name ?? '-' }}@if($outside && $rev === 'pending') <span class="badge bg-warning text-dark ms-1" style="font-size:10px">Perlu Review</span>@endif</div><div class="ka-hrd-meta">{{ $item->attendance_date?->format('d M Y') }} · {{ $item->employee?->department?->name ?? '-' }}</div></div><span class="ka-hrd-pill" style="{{ $outside ? ($rev === 'pending' ? 'background:#f59e0b;color:#1e293b' : ($rev === 'approved' ? 'background:#10b981;color:#fff' : 'background:#ef4444;color:#fff')) : 'background:#e2e8f0;color:#64748b' }}">{{ $outside ? ($rev === 'pending' ? 'Perlu Review' : ($rev === 'approved' ? 'Disetujui' : 'Ditolak')) : 'Aman' }}</span></div><div class="ka-hrd-meta mt-2">{{ $item->workLocation?->name ?? '-' }} · {{ $item->shift?->name ?? '-' }}</div><div class="ka-hrd-meta mt-1">Masuk {{ $item->check_in_at?->format('H:i') ?? '-' }} · Pulang {{ $item->check_out_at?->format('H:i') ?? '-' }} · Telat {{ $item->late_minutes }} menit</div></a>@empty<div class="text-center text-muted py-4">Belum ada data.</div>@endforelse</div><div class="table-responsive ka-hrd-table"><table class="table ka-table"><thead><tr><th>Tanggal</th><th>Karyawan</th><th>Departemen</th><th>Lokasi</th><th>Shift</th><th>Masuk</th><th>Pulang</th><th>Telat</th><th>Radius</th><th>Review</th><th></th></tr></thead><tbody>@forelse($items as $item)
        @php($outside = $needsReview($item))
        @php($rev = $outside ? $reviewStatus($item) : null)
        <tr class="{{ $outside && $rev === 'pending' ? 'table-warning' : '' }}"><td>{{ $item->attendance_date?->format('Y-m-d') }}</td><td>{{ $item->employee?->full_name ?? '-' }}</td><td>{{ $item->employee?->department?->name ?? '-' }}</td><td>{{ $item->workLocation?->name ?? '-' }}</td><td>{{ $item->shift?->name ?? '-' }}</td><td>{{ $item->check_in_at?->format('H:i') ?? '-' }}</td><td>{{ $item->check_out_at?->format('H:i') ?? '-' }}</td><td>{{ $item->late_minutes }} menit</td><td>{{ $outside ? 'Ya' : 'Tidak' }}</td><td>@if($outside)<span class="badge {{ $statusColors[$rev] ?? 'bg-secondary' }}">{{ $rev === 'pending' ? 'Perlu Review' : ($rev === 'approved' ? 'Disetujui' : 'Ditolak') }}</span>@else<span class="text-muted">-</span>@endif</td><td><a href="{{ route('hrd.attendances.show', $item->id) }}" class="btn btn-sm {{ $outside && $rev === 'pending' ? 'btn-warning' : 'btn-primary' }}">Detail</a></td></tr>@empty<tr><td colspan="11" class="text-center text-muted py-4">Belum ada data.</td></tr>@endforelse</tbody></table></div></div><div class="card-footer bg-transparent">{{ $items->links() }}</div></div>
</div>
@endsection
