@extends('layouts.admin.admin')
@section('title', $title)
@include('pages.hrd.partials.mobile-styles')
@section('content')
@include('pages.admin.modules.partials.flash')
<div class="ka-hrd-shell">
    <div class="ka-hrd-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Cek lokasi, catatan, perangkat, dan kebutuhan persetujuan.</p></div><a href="{{ route('hrd.attendances') }}" class="btn btn-light">Kembali</a></div>
    <div class="row g-3">
        <div class="col-lg-8"><div class="card custom-card ka-card"><div class="card-body"><h5>{{ $item->employee?->full_name ?? '-' }}</h5><p class="text-muted mb-3">{{ $item->employee?->department?->name ?? '-' }} · {{ $item->workLocation?->name ?? '-' }}</p><div class="row g-3"><div class="col-6 col-md-4"><div class="ka-detail-box"><b>Tanggal</b><div>{{ $item->attendance_date?->format('d M Y') }}</div></div></div><div class="col-6 col-md-4"><div class="ka-detail-box"><b>Absen Masuk</b><div>{{ $item->check_in_at?->format('Y-m-d H:i') ?? '-' }}</div></div></div><div class="col-6 col-md-4"><div class="ka-detail-box"><b>Absen Pulang</b><div>{{ $item->check_out_at?->format('Y-m-d H:i') ?? '-' }}</div></div></div><div class="col-12 col-md-6"><div class="ka-detail-box"><b>GPS Masuk</b><div>{{ $item->check_in_latitude ?? '-' }}, {{ $item->check_in_longitude ?? '-' }}</div></div></div><div class="col-12 col-md-6"><div class="ka-detail-box"><b>GPS Pulang</b><div>{{ $item->check_out_latitude ?? '-' }}, {{ $item->check_out_longitude ?? '-' }}</div></div></div><div class="col-12"><div class="ka-detail-box"><b>Jarak dari Kantor</b><div>Masuk {{ $item->check_in_distance_meter ?? '-' }} m · Pulang {{ $item->check_out_distance_meter ?? '-' }} m</div></div></div><div class="col-12 col-md-6"><div class="ka-detail-box"><b>Catatan Masuk</b><div>{{ $item->check_in_note ?? '-' }}</div></div></div><div class="col-12 col-md-6"><div class="ka-detail-box"><b>Catatan Pulang</b><div>{{ $item->check_out_note ?? '-' }}</div></div></div><div class="col-12 col-md-6"><div class="ka-detail-box"><b>Perangkat Masuk</b><div class="small">{{ $item->check_in_device_info ?? '-' }}</div></div></div><div class="col-12 col-md-6"><div class="ka-detail-box"><b>Perangkat Pulang</b><div class="small">{{ $item->check_out_device_info ?? '-' }}</div></div></div></div></div></div></div>
        <div class="col-lg-4"><div class="card custom-card ka-card"><div class="card-body"><h5>Persetujuan HRD</h5><p>Perlu dicek: <b>{{ $item->is_need_approval ? 'Ya' : 'Tidak' }}</b></p><p>Catatan: {{ $item->approval_note ?? '-' }}</p><form method="POST" action="{{ route('hrd.attendances.approve', $item->id) }}" class="mb-2">@csrf<textarea name="approval_note" class="form-control mb-2" placeholder="Catatan persetujuan"></textarea><button class="btn btn-success w-100">Setujui</button></form><form method="POST" action="{{ route('hrd.attendances.reject', $item->id) }}">@csrf<textarea name="approval_note" class="form-control mb-2" placeholder="Alasan perlu ditandai" required></textarea><button class="btn btn-danger w-100">Tandai Perlu Perhatian</button></form></div></div></div>
    </div>
</div>
@endsection
