@extends('layouts.admin.admin')
@section('title', $title)
@include('pages.hrd.partials.mobile-styles')
@section('content')
<div class="ka-hrd-shell">
    <div class="ka-hrd-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Laporan absensi harian.</p></div><a href="{{ route('api.hrd.reports.daily-attendance.export', request()->query()) }}" class="btn btn-success">Export CSV</a></div>
    <div class="card custom-card ka-card mb-3"><div class="card-body"><form class="row g-2 ka-hrd-filter">
        <div class="col-6 col-md-2"><input type="date" name="date" value="{{ $date->format('Y-m-d') }}" class="form-control"></div>
        <div class="col-6 col-md-2"><input type="text" name="keyword" value="{{ request('keyword') }}" class="form-control" placeholder="Nama/NIK"></div>
        <div class="col-6 col-md-2"><select name="department_id" class="form-control"><option value="">Departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((int) request('department_id') === $department->id)>{{ $department->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-2"><select name="position_id" class="form-control"><option value="">Position</option>@foreach($positions as $position)<option value="{{ $position->id }}" @selected((int) request('position_id') === $position->id)>{{ $position->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-2"><select name="work_location_id" class="form-control"><option value="">Work Location</option>@foreach($workLocations as $location)<option value="{{ $location->id }}" @selected((int) request('work_location_id') === $location->id)>{{ $location->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-2"><select name="shift_id" class="form-control"><option value="">Shift</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}" @selected((int) request('shift_id') === $shift->id)>{{ $shift->name }}</option>@endforeach</select></div>
        <div class="col-6 col-md-2"><select name="status_id" class="form-control"><option value="">Status</option>@foreach($statuses as $status)<option value="{{ $status->id }}" @selected((int) request('status_id') === $status->id)>{{ friendly_label($status->description) }}</option>@endforeach</select></div>
        <div class="col-6 col-md-2"><select name="work_mode_id" class="form-control"><option value="">Work Mode</option>@foreach($workModes as $mode)<option value="{{ $mode->id }}" @selected((int) request('work_mode_id') === $mode->id)>{{ friendly_label($mode->description) }}</option>@endforeach</select></div>
        <div class="col-6 col-md-2"><select name="radius_status" class="form-control"><option value="">Radius</option><option value="inside" @selected(request('radius_status') === 'inside')>Inside</option><option value="outside" @selected(request('radius_status') === 'outside')>Outside</option></select></div>
        <div class="col-6 col-md-2"><select name="review_status" class="form-control"><option value="">Review</option><option value="pending" @selected(request('review_status') === 'pending')>Pending Review</option><option value="reviewed" @selected(request('review_status') === 'reviewed')>Reviewed</option></select></div>
        <div class="col-12 col-md-2"><button class="btn btn-primary w-100">Filter</button></div>
    </form></div></div>
    <div class="card custom-card ka-card"><div class="card-body"><div class="ka-hrd-card-list">@forelse($items as $item)<div class="ka-hrd-item"><div class="d-flex justify-content-between gap-2"><div><div class="ka-hrd-item-title">{{ $item->employee?->full_name ?? '-' }}</div><div class="ka-hrd-meta">{{ $item->attendance_date?->format('d M Y') }} · {{ $item->employee?->department?->name ?? '-' }} · {{ $item->employee?->position?->name ?? '-' }}</div></div><span class="ka-hrd-pill">{{ friendly_label($item->status?->description) }}</span></div><div class="ka-hrd-meta mt-2">Masuk {{ $item->check_in_at?->format('H:i') ?? '-' }} · Pulang {{ $item->check_out_at?->format('H:i') ?? '-' }} · Telat {{ $item->late_minutes }} menit · Early {{ $item->early_leave_minutes }} menit</div></div>@empty<div class="text-center text-muted py-4">Belum ada data.</div>@endforelse</div><div class="table-responsive ka-hrd-table"><table class="table ka-table"><thead><tr><th>Tanggal</th><th>NIK</th><th>Karyawan</th><th>Departemen</th><th>Position</th><th>Lokasi</th><th>Shift</th><th>Masuk</th><th>Pulang</th><th>Mode In</th><th>Mode Out</th><th>Radius In</th><th>Radius Out</th><th>Telat</th><th>Early</th><th>Total</th><th>Status</th><th>Review</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $item->attendance_date?->format('Y-m-d') }}</td><td>{{ $item->employee?->employee_number ?? '-' }}</td><td>{{ $item->employee?->full_name ?? '-' }}</td><td>{{ $item->employee?->department?->name ?? '-' }}</td><td>{{ $item->employee?->position?->name ?? '-' }}</td><td>{{ $item->workLocation?->name ?? '-' }}</td><td>{{ $item->shift?->name ?? '-' }}</td><td>{{ $item->check_in_at?->format('H:i') ?? '-' }}</td><td>{{ $item->check_out_at?->format('H:i') ?? '-' }}</td><td>{{ friendly_label($item->checkInWorkMode?->description) }}</td><td>{{ friendly_label($item->checkOutWorkMode?->description) }}</td><td>{{ $item->check_in_is_inside_radius === null ? '-' : ($item->check_in_is_inside_radius ? 'Inside' : 'Outside') }}</td><td>{{ $item->check_out_is_inside_radius === null ? '-' : ($item->check_out_is_inside_radius ? 'Inside' : 'Outside') }}</td><td>{{ $item->late_minutes }}</td><td>{{ $item->early_leave_minutes }}</td><td>{{ $item->total_work_minutes }}</td><td>{{ friendly_label($item->status?->description) }}</td><td>{{ $item->is_need_approval ? 'Pending Review' : ($item->approved_at ? 'Reviewed' : '-') }}</td></tr>@empty<tr><td colspan="18" class="text-center text-muted">Belum ada data.</td></tr>@endforelse</tbody></table></div>{{ $items->links() }}</div></div>
</div>
@endsection
