@extends('layouts.admin.admin')
@section('title', $title)
@include('pages.hrd.partials.mobile-styles')
@section('content')
@include('pages.admin.modules.partials.flash')
<div class="ka-hrd-shell">
    <div class="ka-hrd-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Buat dan export rekap absensi bulanan.</p></div><a href="{{ route('api.hrd.reports.monthly-attendance.export', request()->query()) }}" class="btn btn-success">Export CSV</a></div>
    <div class="card custom-card ka-card mb-3"><div class="card-body"><form method="POST" action="{{ route('hrd.reports.monthly-attendance.generate') }}" class="row g-2 ka-hrd-filter">@csrf<div class="col-6 col-md-2"><input type="number" name="year" value="{{ $year }}" class="form-control" placeholder="Tahun"></div><div class="col-6 col-md-2"><input type="number" name="month" value="{{ $month }}" min="1" max="12" class="form-control" placeholder="Bulan"></div><div class="col-6 col-md-2"><button class="btn btn-primary w-100">Generate</button></div></form></div></div>
    <div class="card custom-card ka-card mb-3"><div class="card-body"><form class="row g-2 ka-hrd-filter"><div class="col-6 col-md-2"><input type="number" name="year" value="{{ $year }}" class="form-control" placeholder="Tahun"></div><div class="col-6 col-md-2"><input type="number" name="month" value="{{ $month }}" min="1" max="12" class="form-control" placeholder="Bulan"></div><div class="col-6 col-md-3"><input type="text" name="keyword" value="{{ request('keyword') }}" class="form-control" placeholder="Nama/NIK"></div><div class="col-6 col-md-3"><select name="department_id" class="form-control"><option value="">Departemen</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((int) request('department_id') === $department->id)>{{ $department->name }}</option>@endforeach</select></div><div class="col-12 col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form></div></div>
    <div class="card custom-card ka-card"><div class="card-body"><div class="ka-hrd-card-list">@forelse($items as $item)<div class="ka-hrd-item"><div class="d-flex justify-content-between gap-2"><div><div class="ka-hrd-item-title">{{ $item->employee?->full_name ?? '(Karyawan Dihapus)' }}</div><div class="ka-hrd-meta">{{ $item->employee?->employee_number ?? '-' }} · {{ $item->employee?->department?->name ?? '-' }} · {{ $item->employee?->position?->name ?? '-' }}</div></div><span class="ka-hrd-pill">{{ $item->total_present }} hadir</span></div><div class="ka-hrd-meta mt-2">Telat {{ $item->total_late }} · Sakit {{ $item->total_sick }} · Cuti {{ $item->total_leave }} · Izin {{ $item->total_permission }}</div><div class="ka-hrd-meta mt-1">Belum lengkap {{ $item->total_incomplete }} · Luar radius {{ $item->total_outside_radius }} · {{ $item->total_work_minutes }} menit kerja</div></div>@empty<div class="text-center text-muted py-4">Belum ada data. Generate dulu.</div>@endforelse</div><div class="table-responsive ka-hrd-table"><table class="table ka-table"><thead><tr><th>Year</th><th>Month</th><th>NIK</th><th>Karyawan</th><th>Departemen</th><th>Position</th><th>Work Days</th><th>Present</th><th>Late</th><th>Absent</th><th>Sick</th><th>Leave</th><th>Permission</th><th>Incomplete</th><th>Outside</th><th>Work Minutes</th><th>Late Minutes</th><th>Early Minutes</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $item->year }}</td><td>{{ $item->month }}</td><td>{{ $item->employee?->employee_number ?? '-' }}</td><td>{{ $item->employee?->full_name ?? '-' }}</td><td>{{ $item->employee?->department?->name ?? '-' }}</td><td>{{ $item->employee?->position?->name ?? '-' }}</td><td>{{ $item->total_work_days }}</td><td>{{ $item->total_present }}</td><td>{{ $item->total_late }}</td><td>{{ $item->total_absent }}</td><td>{{ $item->total_sick }}</td><td>{{ $item->total_leave }}</td><td>{{ $item->total_permission }}</td><td>{{ $item->total_incomplete }}</td><td>{{ $item->total_outside_radius }}</td><td>{{ $item->total_work_minutes }}</td><td>{{ $item->total_late_minutes }}</td><td>{{ $item->total_early_leave_minutes }}</td></tr>@empty<tr><td colspan="18" class="text-center text-muted">Belum ada data.</td></tr>@endforelse</tbody></table></div>{{ $items->links() }}</div></div>
</div>
@endsection
