@extends('layouts.admin.admin')
@section('title', $title)
@section('content')
<div class="ka-toolbar"><div><h2 class="ka-page-title">{{ $title }}</h2><p class="ka-page-subtitle">Ringkasan data user, employee, saldo cuti, absensi, leave, dan koreksi.</p></div><div class="d-flex gap-2"><a href="{{ route('admin.employees.edit', $user->id) }}" class="btn btn-primary">Edit</a><a href="{{ route('admin.employees') }}" class="btn btn-light">Kembali</a></div></div>
<div class="row g-3">
    <div class="col-lg-4"><div class="card custom-card ka-card"><div class="card-body text-center">@if($profileImageUrl)<img src="{{ $profileImageUrl }}" alt="Profile" class="rounded-circle mb-3" style="width:92px;height:92px;object-fit:cover">@endif<h4>{{ $employee?->full_name ?? $user->name }}</h4><p class="text-muted mb-2">{{ $user->email }}</p><span class="badge bg-primary">{{ $user->role?->name ?? '-' }}</span></div></div></div>
    <div class="col-lg-8"><div class="card custom-card ka-card"><div class="card-body"><h5>Data Employee</h5><div class="row g-3"><div class="col-md-4"><b>NIK</b><div>{{ $employee?->employee_number ?? '-' }}</div></div><div class="col-md-4"><b>Department</b><div>{{ $employee?->department?->name ?? '-' }}</div></div><div class="col-md-4"><b>Position</b><div>{{ $employee?->position?->name ?? '-' }}</div></div><div class="col-md-4"><b>Work Location</b><div>{{ $employee?->workLocation?->name ?? '-' }}</div></div><div class="col-md-4"><b>Shift</b><div>{{ $employee?->shift?->name ?? '-' }}</div></div><div class="col-md-4"><b>Status</b><div>{{ $employee?->is_active ? 'Aktif' : 'Tidak Aktif' }}</div></div></div></div></div></div>
    <div class="col-lg-4"><div class="card custom-card ka-card"><div class="card-body"><h5>Summary Bulan Ini</h5><div>Present: <b>{{ $attendanceSummary['present'] ?? 0 }}</b></div><div>Late: <b>{{ $attendanceSummary['late'] ?? 0 }}</b></div><div>Outside Radius: <b>{{ $attendanceSummary['outside'] ?? 0 }}</b></div></div></div></div>
    <div class="col-lg-8"><div class="card custom-card ka-card"><div class="card-body"><h5>Saldo Cuti</h5><div class="table-responsive"><table class="table ka-table"><thead><tr><th>Tahun</th><th>Jenis</th><th>Total</th><th>Terpakai</th><th>Sisa</th></tr></thead><tbody>@forelse($leaveBalances as $balance)<tr><td>{{ $balance->year }}</td><td>{{ friendly_label($balance->leaveType?->description) }}</td><td>{{ $balance->total_quota }}</td><td>{{ $balance->used_quota }}</td><td>{{ $balance->remaining_quota }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Belum ada saldo.</td></tr>@endforelse</tbody></table></div></div></div></div>
    <div class="col-lg-12"><div class="card custom-card ka-card"><div class="card-body"><h5>Absensi Terakhir</h5><div class="table-responsive"><table class="table ka-table"><thead><tr><th>Tanggal</th><th>Masuk</th><th>Pulang</th><th>Status</th><th>Telat</th></tr></thead><tbody>@forelse($recentAttendances as $attendance)<tr><td>{{ $attendance->attendance_date?->format('Y-m-d') }}</td><td>{{ $attendance->check_in_at?->format('H:i') ?? '-' }}</td><td>{{ $attendance->check_out_at?->format('H:i') ?? '-' }}</td><td>{{ friendly_label($attendance->status?->description) }}</td><td>{{ $attendance->late_minutes }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Belum ada data.</td></tr>@endforelse</tbody></table></div></div></div></div>
    <div class="col-lg-6"><div class="card custom-card ka-card"><div class="card-body"><h5>Leave Terakhir</h5>@forelse($recentLeaves as $leave)<div class="border-bottom py-2">{{ $leave->start_date?->format('Y-m-d') }} - {{ $leave->end_date?->format('Y-m-d') }} · {{ friendly_label($leave->leaveType?->description) }} · <b>{{ friendly_label($leave->status?->description) }}</b></div>@empty<div class="text-muted">Belum ada leave.</div>@endforelse</div></div></div>
    <div class="col-lg-6"><div class="card custom-card ka-card"><div class="card-body"><h5>Koreksi Terakhir</h5>@forelse($recentCorrections as $correction)<div class="border-bottom py-2">{{ $correction->correction_date?->format('Y-m-d') }} · <b>{{ friendly_label($correction->status?->description) }}</b> · {{ $correction->reason }}</div>@empty<div class="text-muted">Belum ada koreksi.</div>@endforelse</div></div></div>
</div>
@endsection
